### ISSUE TITLE
I'll say this nicely as possible 

### ISSUE THREAD

**Issue by PROBLEMCHYLD** [frimtec/secure-sms-proxy#216]
I reported a bug and you think I'm playing games? I don't even play with my kids let along grown-ups.

When I installed the latest version it was not working until I deleted the contacts from Operations Center and had to re-add them. This didn't happen on my Android 9 phone, only on my Android 13 OnePlus 8T. Even the send test Sms wasn't working until I deleted contacts. Whether you add the feature (to delete contacts individually or all at once) or not I know how to improvise. This is what I do, test software, report bugs and go about my day. Nothing more nothing less.

P.S

Imagine having an app on your phone full of contacts stored and the only way to remove old or non-working numbers is to have to delete them all because that's how the app is designed. I guess in the world of programming/developing it is the ideal thing. Anyways thanks for a good app.👍

**Comment by frimtec** [comment]
Sorry, but I just don't understand your use case and your bug.
To understand your problem please make some screenshots that show all your steps and the error behavior.

Please understand that I can not investigate with the context you gave. Especially as I can not find any problems after updating S2MSP on all my test environments.

**Comment by PROBLEMCHYLD** [comment]
In the first image I run a test and nothing happens. In the second image I run a test and nothing happens unless I delete the Contacts from Operations Center. The only annoyance is instead of deleting an individual contact, all are deleted and have to constantly be re-added. Other than that I don't have an issue. IDK if it's an Android 13 bug because it doesn't do it on my Android 9 phone. This only seems to happen when I update.

![Screenshot_2023-05-01-03-50-08-24_2db2eb5db1f1f09ac9d1d1969c3e9706](https://user-images.githubusercontent.com/30463992/235431951-4989133b-7a1b-4f4c-bda5-7a208317ea57.jpg)
![Screenshot_2023-05-01-03-55-59-31_2db2eb5db1f1f09ac9d1d1969c3e9706](https://user-images.githubusercontent.com/30463992/235431967-8ca5f3a6-bcc9-4d34-8e6b-30367bca4124.jpg)

**Comment by frimtec** [comment]
Thanks @PROBLEMCHYLD  for the screenshots.

If the "Test-SMS received!" message does not show up, means the SMS-Loopback between PAssist and S2MSP is broken.
This is usualy the case when the secred for the communication encryption between the two apps is not equal.
Deleting the contacs and re-adding them solves the issue as this renews the secret.
But this is not nescessary. Re-starting PAssist should do the job as well, as PAssist re-initilizes the communication secret on each start (just stop the app completly via a phone restart or the terminat menu option on the apps info button).

Normaly the secret should not get out of sync even on a S2MSP update. I can't reproduce that when updating S2MSP. I always test intensivly with the latest Android version, currently 13. 
My test devices are the android simulator and two physical phones (Pixel 4a and Pixel 7).
Maybe the problem has to do with the OnePlus 8T. I don't have such a device.

If the problem happens again, please try to collect the logs from PAssist and S2MSP directly after the missing "Test-SMS received!" message.
If you enable the developer mode on your phone, you will get an additional menu option "Logcat" in PAssist and in S2MSP where you can see and copy&past the logs from.
Send me the logs, maybe I can find the cause for your issue.
After that, just try the workaround with stopping PAssist and try again without deleting the phone numers. 
I'm quite sure, that it will solve the issue as well.

Hope that helps.
regards, @frimtec

**Comment by PROBLEMCHYLD** [comment]
I don't have access to developer mode. I can't even root my phone because of the provider. How else can I get a log to you?

**Comment by frimtec** [comment]
You don't need to root your device for developer mode.
Jsut follow the following instruction: https://developer.android.com/studio/debug/dev-options

**Comment by frimtec** [comment]
What do you mean with "When I put the app lock on S2MSP with a fingerprint"?
I'm confused.
Do you mean you can reproduce the issue with an other scenario beside updating S2MSP?

**Comment by frimtec** [comment]
One last idea: disable the battery optimization for S2MSP. Maybe your phone is too aggressive with the energy saving.
Normally events of the kind used between PAssist and S2MSP are not affected by power saving strategies, but you never know. Some companies do a bit too much to make thair battery runtime look better then it is.

If this does not help, I guess there is nothing more I can help - except if I would see the logs.

**Comment by PROBLEMCHYLD** [comment]
What I'm saying is, my applications on Android has a fingerprint lock to access them. In order to access anything on my phone you need a pin or fingerprint. S2MSP are one of those applications. When I disabled the fingerprint lock on the application S2MSP everything started to work.

**Comment by PROBLEMCHYLD** [comment]
Turning on "Don't Optimize" did the trick for now. Thanks for the suggestion.
